server.port=8080
spring.application.name=laese-gallery

spring.datasource.url=jdbc:postgresql://localhost:5432/GaleriaRelojes
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# "update" crea la tabla si no existe y no borra datos existentes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Carga data.sql automaticamente al arrancar (inserta los relojes si no existen)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true